---

- hosts: pipeline

  tasks:

  - name: Make sure Zookeeper, PostgreSQL and Pipeline  services ar running
    systemd:
      state: started
      daemon_reload: yes
      enabled: yes
      name: "{{ item.name }}"
    with_items:
      - { name: otif-ingestion-api-1 }
      - { name: ot-zk-1 }
      - { name: postgresql-9.4 }


  - name: Wait for Pipeline on port 7071. Zookeeper on port 2181 and PostgreSQL on 5432.
    wait_for:
      host: "127.0.0.1"
      port: "{{ item.port }}"
      delay: 5
      state: started
    with_items:
      - { port: 7071 }
      - { port: 2181 }
      - { port: 5432 }
