---
# defaults file for install_wsm_crawler

otif_wsm_crawler_package: infofusion-crawler_web-social-media_installer-16.2.0.2-linux.bin

USER_INSTALL_DIR: /opt/infofusion-16.2/wsm-crawler

wsm_crawler_deamon_user: wsm-crawler

remove_wsm_crawler: True

