---

- name: Open port 9092 for Kafka (Error reported but ignored if firewall is not active)
  become: true
  ignore_errors: yes
  firewalld:
    zone: public
    port: "{{item}}/tcp"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "9092"
