---

- name: Wait until Zookeeper is listening on port 2181 (mandatory)
  wait_for:
    host: "{{ zookeeper_hostname }}"
    port: "{{ item.port }}"
    delay: 5
    timeout: 10
    state: started
  with_items:
    - { port: 2181 }
  register: wait

- name: Mount DVD at {{ default_installer_location }}. Kafka installer is expected to be there.
  mount:
    path: "{{ default_installer_location }}"
    src: /dev/cdrom
    fstype: udf
    state: mounted

- name: Find kafka installer package in '{{ default_installer_location }}'
  find:
    paths: "{{ default_installer_location }}"
    patterns: "^.*kafka.*\\.bin$"
    use_regex: yes
  register: kafka_installer

- fail:
    msg: "No kafka installer found in {{ default_installer_location }}"
  when: kafka_installer.matched == 0

- name: Install Python dependencies ...
  yum:
    name: "{{ item }}"
  with_items:
    - python-setuptools
    - gcc
    - make
    - python-devel
    - libxml2-devel
    - libxslt-devel

- name: Install Python libraries ...
  become: true
  easy_install:
    name: "{{ item }}"
  with_items:
    - pexpect
    - lxml

- name: Make sure Kafka is removed if it exists
  block:

    - name: Check if Kafka is in the InstallAnywhere registry
      stat:
        path: /var/.com.zerog.registry.xml
      register: installanywhere_registry_is_there
    
    - name: If Registry is present ...
      block:

        - name: Look if kafka is already registred
          xml:
            path: /var/.com.zerog.registry.xml
            xpath: /registry/products/product//feature[@short_name='Kafka']
            count: yes
          register: hits
          when: installanywhere_registry_is_there.stat.exists == true

        - name: Get location where kafka is already installed
          xml:
            path: /var/.com.zerog.registry.xml
            xpath: /registry/products/product[@name='Kafka Server for OpenText InfoFusion']
            content: attribute
            attribute: location
          register: kafka_location
          when: hits.count > 0

        - debug:
            msg: "Kafka is already installed in {{ kafka_location.matches[0].product.location }}."
          when: hits.count > 0

        - name: Removing Kafka ...
          expect:
            command: "{{ kafka_installer.files[0].path }} -i console"
            echo: yes
            timeout: 30
            responses:
              .*Choose Instance Management Option.*: "2"
              .*Choose the instance to modify.*: "1"
              .*DEFAULT.*: "1"
              .*TO CONTINUE.*: ""
          when: hits.count > 0

        - name: Removing Kafka directory
          file:
            path: "{{ item }}"
            state: absent
          with_items:
            - "{{ kafka_location.matches[0].product.location }}"
          when: hits.count > 0  

      when: installanywhere_registry_is_there.stat.exists == true

  when: remove_kafka

#- pause:
#    prompt: "Kafka should not be there!"

- debug:
    msg: "Kafka will be installed using '{{ kafka_installer.files[0].path }}'"

- debug:
    msg: "Kafka will be installed in {{ kafka_installation_path }}"

#- pause:
#    prompt: "PRESS <ENTER> TO START"

- name: Execute Kafka installer in console mode
  expect:
    command: "{{ kafka_installer.files[0].path }} -i console"
    echo: yes
    timeout: 30
    responses:
      .*to reach the end of this text.*: "skip"
      PRESS \<ENTER\> TO CONTINUE: ""
      .*DO YOU ACCEPT THE TERMS.*: "Y"
      .*ENTER AN ABSOLUTE PATH.*: "{{ kafka_installation_path }}"
      .*IS THIS CORRECT.*: "Y"
      .*Current Host.*: ""
      .*Zookeeper Host.*: "{{ zookeeper_hostname }}"
      .*YOUR CHOICE.*: "1"
      .*EXIT THE INSTALLER.*: ""

