---

- name: Check that the installer exists and is executable
  file:
    path: "{{download_folder}}/{{kafka_installer_package}}"
    state: touch
    owner: "{{ playbook_user }}"
    group: "{{ playbook_user }}"
    mode: "u+x"

# To uninstall 
# .*Choose Instance Management Option.*  : '2'
# .*Choose the instance to modify.*   : '1'
# .*DEFAULT.* : '1'
# .* TO CONTINUE.* : ''


- name: Install pexpect dependency
  become: true
  easy_install:
    name: pexpect 
    state: latest

- name: Create a group for Kafka user
  group:
    name: kafka
    state: present

- name: Create user that will run Kafka deamon
  user:
    name: kafka
    group: kafka
    comment: "This user manages Kafka deamon"

- name: Execute Kafka installer in console mode
  expect:
    command: "{{ download_folder }}/{{ kafka_installer_package }} -i console"
    creates: "{{ kafka_destination_path }}"
    echo: true
    timeout: 10
    responses:
      PRESS \<ENTER\> TO CONTINUE.* : ''
      .*type ''skip''.*             : 'skip'
      .*LICENSE AGREEMENT.*         : 'Y'
      .*ABSOLUTE PATH.*             : '{{ kafka_destination_path }}'
      .*IS THIS CORRECT.*           : 'Y'
      .*Current Host.*              : '{{ kafka_host }}'
      .*Zookeeper Host.*            : '{{ zookeeper_host }}'
    
- name: Wait Kafka to be listening on port 9092 
  wait_for:
    host: "127.0.0.1"
    port: "{{ item }}"
    delay: 5
    state: started
  with_items:
    - "9092"
