---

- name: Make sure download folder exists
  include_role: 
    name: common
    tasks_from: create_download_folder.yml

- name: Make sure Kafka and Zookeeper are not already running
  systemd:
    state: stopped
    name: "{{ item.name }}"
  with_items:
    - { name: zookeeper }
    - { name: kafka }

- name: Remove existing instalation
  block:

    - name: Delete existing download 
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ download_folder }}/{{ kafka_package_url | basename}}"
        - "/opt/kafka"
        - "/opt/{{  kafka_package_url | basename | regex_replace('\\.[^.]+$') }}"
        - "/var/lib/zookeeper"
        - "/var/lib/kafka"
        - "/etc/systemd/system/zookeeper.service"        
        - "/etc/systemd/system/kafka.service"

  when: remove_kafka

- name: Download Kafka package
  get_url:
    url: "{{ kafka_package_url }}"
    dest: "{{ download_folder }}"
    owner: "{{ playbook_user }}"
    group: "{{ playbook_user }}"
  register: kafka_package

- name: Create a group for Kafka user
  group:
    name: kafka
    state: present

- name: Create user that will run Kafka deamon
  user:
    name: kafka
    group: kafka
    comment: "This user manages Kafka deamon"    

- name: Extract Kafka from the package
  unarchive:
    src: "{{ kafka_package.dest }}"
    dest: "/opt"
    owner: kafka
    group: kafka
    
- name: Create a link for the Kafka install folder
  file:
    src: "/opt/{{ kafka_package.dest | basename | regex_replace('\\.[^.]+$') }}"
    dest: "/opt/kafka"
    state: link
    owner: kafka
    group: kafka

