---

- debug:
    msg: "Kafka will be installed using '{{ kafka_installer.path }}'"

- debug:
    msg: "Kafka will be installed in {{ kafka_installation_path }}"

- name: Execute Kafka installer in console mode
  expect:
    command: "{{ kafka_installer.path }} -i console"
    echo: yes
    timeout: 30
    responses:
      .*to reach the end of this text.*: "skip"
      PRESS \<ENTER\> TO CONTINUE: ""
      .*DO YOU ACCEPT THE TERMS.*: "Y"
      .*ENTER AN ABSOLUTE PATH.*: "{{ kafka_installation_path }}"
      .*IS THIS CORRECT.*: "Y"
      .*Current Host.*: ""
      .*Zookeeper Host.*: "{{ zookeeper_hostname }}"
      .*YOUR CHOICE.*: "1"
      .*EXIT THE INSTALLER.*: ""
  register: installer_output

- debug:
    var: installer_output.stdout_lines

- pause:
    prompt: "Installation completed. Kafka should have been installed."
  when: with_pause
