---
# tasks file for install_kafka

- name: Deploy Apache Kafka
  block:

    - name: Install Apache Kafka
      include_tasks: install_kafka.yml

    - name: Configure Apache Kafka
      include_tasks: configure_kafka.yml

    - name: Start Apache Kafka
      include_tasks: start_kafka.yml

  when: inventory_hostname in groups['kafka']
