---

- name: start Kafka service
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item.name }}"
  with_items:
    - { name: kafka }

- name: Wait until Kafka is listening on port 9092
  wait_for:
    host: "{{ kafka_hostname }}"
    port: "{{ item.port }}"
    delay: 5
    state: started
  with_items:
    - { port: 9092 }



