---

#    - name: Get IP Addresses
#      debug: var=ansible_all_ipv4_addresses
#    - debug: var=ansible_default_ipv4.address
#    - debug: var=ansible_default.eth0.address
#      debug: var=ansible_enp0s3.ipv4.address
#    - debug: var=ansible_enp0s8.ipv4.address
#    - debug: var=ansible_virbr0.ipv4.address
#    - debug: var=inventory_hostname
#    - debug: var=ansible_domain
#    - debug: var=ansible_fqdn
#    - debug: var=group_names

     - name: Generating /etc/hosts file and restart network.service
       become: true
       template:
         src=hosts.j2
         dest=/etc//hosts
       notify: restart-network
       when: overwrite == "yes"

     - name: Generating /etc/ansible hosts file if 'overwrite == yes'
       become: true
       template:
         src=hosts.j2
         dest=/etc/ansible-hosts
       when: overwrite != "yes"
