---
# tasks file for configure_pipeline

- name: Open ports 7071 & 7171 used by Pipeline service.
  become: yes
  ignore_errors: yes
  firewalld:
    zone: public
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "7071"
    - "7171"

- name: Initialize the database used by the Pipeline
  shell: "{{ item.command }}"
  with_items:
    - { command: "PGPASSWORD={{ master_password }} psql {{ master_username }} -d {{ master_dbname }} -f {{ pipeline_installation_path }}/etc/ingestion-api/defaults-dbadapter/postgresql/dbAdapterConfig-postgresql-sql-tables.sql" }
 
