---
# tasks file for install_zookeeper

- name: Open port 2181 used by Zookeeper service
  become: yes
  ignore_errors: yes
  firewalld:
    zone: public
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "2181" 
