---
# tasks file for configure_pipeline

- name: Open ports 7071 & 7171 used by Pipeline service.
  become: yes
  ignore_errors: yes
  firewalld:
    zone: public
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "7071"
    - "7171"

- name: Initialize the database used by the Pipeline
  shell: "{{ item.command }}"
  with_items:
    - { command: "PGPASSWORD={{ master_password }} psql {{ master_username }} -d {{ master_dbname }} -f {{ pipeline_installation_path }}/etc/ingestion-api/defaults-dbadapter/postgresql/dbAdapterConfig-postgresql-sql-tables.sql" }


- name: Authenticate to the Dashboard  UI to get cookie
  uri:
    url: "http://{{ dashboard_hostname }}:10020/otif-dashboard-api/api/v1/authenticate/login"
    method: POST
#    body: "username={{ master_username }}&password={{ master_password }}"
    body: "username=admin&password=admin"
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login

- name: Register Pipeline in the Dashboard
  uri:
    url: "http://{{ dashboard_hostname }}:10020/otif-dashboard-api/api/v1/pipeline/register"
    method: POST
    body: >
        {
           "host":"{{ pipeline_hostname }}",
           "port":7071,
           "basePath":"/",
           "adminUrl":"http://{{ pipeline_fqdn }}:7171",
           "componentName":"Ingestion Pipeline-1"
        }
    status_code: 201, 400
    body_format: json
    timeout: 30
  register: request_otif

- name:
  debug:
    var: request_otif

