---
# tasks file for install_pipeline

- name: Prepare Installation
  include_tasks: checkup.yml

- name: Check if Pipeline needs to be removed ...
  include_role:
    name: remove_pipeline
    tasks_from: remove_pipeline
  when: remove_pipeline

- name: Install  InfoFusion Ingestion Pipeline
  include_tasks: install_pipeline.yml

- name: Configure InfoFusion Ingestion Pipeline
  include_tasks: configure_pipeline.yml

- name: Start InfoFusion Ingestion Pipeline
  include_tasks: start_pipeline.yml




