---
# tasks file for install_pipeline

- name: Install  InfoFusion Ingestion Pipeline
  include_tasks: install_pipeline.yml

- name: Configure InfoFusion Ingestion Pipeline
  include_tasks: configure_pipeline.yml

- name: Start InfoFusion Ingestion Pipeline
  include_tasks: start_pipeline.yml




