---

- name: Cleanup disk and delete temp files ...
  shell: rm -rf /tmp/install.dir*

- name: Install Python dependencies ...
  yum:
    name: "{{ item }}"
  with_items:
    - python-setuptools
    - gcc
    - make
    - python-devel
    - libxml2-devel
    - libxslt-devel

- name: Install Python libraries ...
  become: true
  easy_install:
    name: "{{ item }}"
  with_items:
    - lxml

- name: Install pexpect dependency
  become: true
  ignore_errors: yes
  easy_install:
    name: pexpect
  register: pexpect_result

- debug:
    var: pexpect_result

- name: Fallback in case previous easy_install pexect didn't work
  command: easy_install pexpect
  when: pexpect_result.failed == true

- name: Mount DVD at {{ default_installer_location }}. Ingestion Pipeline Installer is exepected to be there
  mount:
    path: "{{ default_installer_location }}"
    src: /dev/cdrom
    fstype: udf
    state: mounted

- name: Find Pipeline installer package in '{{ default_installer_location }}'
  find:
    paths: "{{ default_installer_location }}"
    patterns: "^.*pipeline-installer.*\\.bin$"
    use_regex: yes
  register: pipeline_installer

- fail:
    msg: "No Pipeline installer found in {{ default_installer_location }}"
  when: pipeline_installer.matched == 0

