---
# tasks file for configure_pipeline

- name: start Pipeline services
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item.name }}"
  with_items:
    - { name: otif-ingestion-api-1 }

- name: Wait until Pipeline is listening on ports 7071 & 7171  
  wait_for:
    host: "{{ pipeline_hostname }}"
    port: "{{ item.port }}"
    delay: 5
    state: started
  with_items:
    - { port: 7071 }
    - { port: 7171 }

- name:
  vars:
    msg: |
         Magellan Crawler Pipeline has been configured on {{ pipeline_hostname }}.
         You can validate deployement by opening http://{{ pipeline_fqdn }}:7171
         or http://{{ ansible_host }}:7171
         Default credentials are admin/admin.
  debug:
    msg: "{{ msg.split('\n') }}"
