---
# tasks file for configure_pipeline

- name: start Pipeline services
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item.name }}"
  with_items:
    - { name: otif-ingestion-api-1 }

- name: Wait until Pipeline is listening on ports 7071 & 7171  
  wait_for:
    host: "{{ pipeline_hostname }}"
    port: "{{ item.port }}"
    delay: 5
    timeout: 20
    state: started
  with_items:
    - { port: 7071 }
    - { port: 7171 }

- name: Register Pipeline in the Dashboard
  uri:
    url: "http://{{ pipeline_hostname }}:7171/otif/v3/admin/dashboardNotifier"
    method: PUT
    body: >
      { "type": "dashboardNotifierConfig", "version": "0", "enabled": { "value": "true", "defaultValue": "false" },
      "dashboardHost": "{{ dashboard_hostname }}","dashboardPort": {"value": "10020","defaultValue": "10020" },
      "dashboardPath": { "value": "/otif-dashboard-api/api/v1","defaultValue": "/otif-dashboard-api/api/v1" },
      "dashboardUser": "admin","dashboardPassword": "admin" }
    force_basic_auth: yes
    user: "admin"
    password: "admin"
    status_code: 202
    body_format: json
    timeout: 30
  register: request_otif

- name:
  debug:
    var: request_otif


- name:
  vars:
    msg: |
         Magellan Crawler Pipeline has been configured on {{ pipeline_hostname }}.
         You can validate deployement by opening http://{{ pipeline_fqdn }}:7171
         or http://{{ ansible_host }}:7171
         Default credentials are admin/admin.
  debug:
    msg: "{{ msg.split('\n') }}"
