---
# tasks file for configure_pipeline

- name: start Pipeline services
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item.name }}"
  with_items:
    - { name: otif-ingestion-api-1 }

- name: Wait until Pipeline is listening on port 7171
  wait_for:
    host: 127.0.0.1
    port: "{{ item.port }}"
    delay: 5
    state: started
  with_items:
    - { port: 7171 }
