---
# defaults file for install_mongodb

mongo_version: '3.4'

mongo_packages: mongodb-org

mongo_repo_gpgcheck: True

mongo_repo_baseurl: "https://repo.mongodb.org/yum/redhat/{{ ansible_distribution_major_version }}/mongodb-org/{{ mongo_version }}/x86_64/"
mongo_repo_gpgkey:  "https://www.mongodb.org/static/pgp/server-{{ mongo_version }}.asc"


remove_mongodb: true

# WARNING! If the following is set to true, all existing collections will be erased during installation.
remove_mongo_data: true 

mongo_config: /etc/mongod.conf
mongo_port: 27017

mongo_database: "{{ master_dbname }}"
mongo_user: "{{ master_username }}"
mongo_pw: "{{ master_password }}"

mongo_packages_dependencies:
  - libselinux-python
