---
# defaults file for install_kafka

# Note: Location of the installer is defined with global variable {{ installer_location }}
#       Selection of the bin file to used is based on a lookup in the location for a file
#       matching the regex ^.*kafka.*\\.bin$

# Where to install Kafka - Change as needed
# kafka_installation_path: "/opt/infofusion-16.4/kafka"
kafka_installation_path: "{{ default_installation_path }}/kafka"


# Both Kafka are setup to run on their default ports. Role would need to be changed
# to used the commented variable below if custom ports are needed.
#kafka_port: 9092
#zookeeper_port: 2181


# Remove existing Kafka
remove_kafka: True

# Delete associated node and information in Zookeeper
cleanup_zookeeper: true

with_pause: False
skip_zk: False
