---
# defaults file for install_kafka

# Name of  the Kafka installer package
kafka_installer_package: "infofusion-kafka-installer-0.0.1-20180201.211732-218-linux.bin"

# Where to install Kafka
kafka_destination_path: "/opt/infofusion-16.4/kafka"

# Both Kafka are setup to run on their default ports. Role would need to be changed
# to used the commented variable below if custom ports are needed.
#kafka_port: 9092
#zookeeper_port: 2181


# Remove existing Kafka
remove_kafka: True
