# Global variables

otif_version: "16.4"

with_pause: false

timestamp: "{{ ansible_date_time.date }}"

installation_method: download
#installation_method: iso
#installation_method: file

# Default path for installation
default_installation_path: "/OpenText/infofusion-{{otif_version}}"
#default_installation_path: "/opt/OpenText/infofusion-{{otif_version}}"

# Location of the mounted iso containing InfoFusion installers
#default_installer_location: "/mnt/dvd"
default_installer_location: "/temp"

# Download path. Access to OT network needed.
download_text_mining_bin: ftp://ci:ci@discovery-nexus.lab.opentext.com/ftp-home/tme-downloads/main/com/nstein/tme/tme-bin/16.4.0.2/tme-16.4.0.2-bin.zip
download_text_mining_data: ftp://ci:ci@discovery-nexus.lab.opentext.com/ftp-home/tme-downloads/main/com/nstein/tme/tme-data/16.4.0.2/tme-16.4.0.2-data.zip
download_zookeeper: http://discovery-nexus.lab.opentext.com:8081/nexus/content/repositories/releases/com/opentext/discovery/infofusion-zookeeper-installer/16.4.0.3/infofusion-zookeeper-installer-16.4.0.3-linux.bin
download_kafka: http://discovery-nexus.lab.opentext.com:8081/nexus/content/repositories/releases/com/opentext/discovery/infofusion-kafka-installer/16.4.0.3/infofusion-kafka-installer-16.4.0.3-linux.bin
download_wsm_crawler: http://is-art.hcl.com:8080/nexus/content/repositories/releases/com/opentext/magellan/crawlersinstaller/infofusion-crawler-web-social-media-installer/16.4.0.3/infofusion-crawler-web-social-media-installer-16.4.0.3-linux.bin
download_pipeline: http://discovery-nexus.lab.opentext.com:8081/nexus/content/repositories/releases/com/opentext/otif/infofusion-ingestion-pipeline-installer/16.4.0.3/infofusion-ingestion-pipeline-installer-16.4.0.3-linux.bin
download_dashboard: http://discovery-nexus.lab.opentext.com:8081/nexus/content/repositories/releases/com/opentext/otif/infofusion-dashboard/16.4.0.3/infofusion-dashboard-16.4.0.3.zip
#download_dashboard: http://discovery-nexus.lab.opentext.com:8081/nexus/content/repositories/snapshots/com/opentext/otif/infofusion-dashboard/0.0.1-SNAPSHOT/infofusion-dashboard-0.0.1-20180416.195015-35.zip

download_is: http://is-art.hcl.com:8080/nexus/content/repositories/releases/com/opentext/infofusion/is/infofusion-integration-services-installer/
download_ecm_crawler: http://is-art.hcl.com:8080/nexus/content/repositories/releases/com/opentext/infofusion/crawler/infofusion-crawler-ecm-installer/
download_ecm_project: http://is-art.hcl.com:8080/nexus/content/repositories/releases/com/opentext/infofusion/crawler/ifcrawler-otic-projects-zip/

# Default domain
domain: "{{hostvars[ansible_hostname]['ansible_domain']}}"

zookeeper_host: "{{hostvars[inventory_hostname]['groups']['zookeeper'][0]}}"
zookeeper_hostname: "{{hostvars[zookeeper_host]['ansible_hostname']}}"
zookeeper_fqdn: "{{hostvars[zookeeper_host]['ansible_fqdn'] | regex_replace('\\.$', '')}}"

kafka_host: "{{hostvars[inventory_hostname]['groups']['kafka'][0]}}"
kafka_hostname: "{{hostvars[kafka_host]['ansible_hostname']}}"
kafka_fqdn: "{{hostvars[kafka_host]['ansible_fqdn'] | regex_replace('\\.$', '')}}"

wsm_crawler_host: "{{hostvars[inventory_hostname]['groups']['wsm-crawler'][0]}}"
wsm_crawler_hostname: "{{hostvars[wsm_crawler_host]['ansible_hostname']}}"
wsm_crawler_fqdn: "{{hostvars[wsm_crawler_host]['ansible_fqdn'] | regex_replace('\\.$', '')}}"

pipeline_host: "{{hostvars[inventory_hostname]['groups']['pipeline'][0]}}"
pipeline_hostname: "{{hostvars[pipeline_host]['ansible_hostname']}}"
pipeline_fqdn: "{{hostvars[pipeline_host]['ansible_fqdn'] | regex_replace('\\.$', '')}}"

text_mining_host: "{{hostvars[inventory_hostname]['groups']['text-mining'][0]}}"
text_mining_hostname: "{{hostvars[text_mining_host]['ansible_hostname']}}"
text_mining_fqdn: "{{hostvars[text_mining_host]['ansible_fqdn'] | regex_replace('\\.$', '')}}"

mongodb_host: "{{hostvars[inventory_hostname]['groups']['mongodb'][0]}}"
mongodb_hostname: "{{hostvars[mongodb_host]['ansible_hostname']}}"
mongodb_fqdn: "{{hostvars[mongodb_host]['ansible_fqdn'] | regex_replace('\\.$', '')}}"

dashboard_host: "{{hostvars[inventory_hostname]['groups']['dashboard'][0]}}"
dashboard_hostname: "{{hostvars[dashboard_host]['ansible_hostname']}}"
dashboard_fqdn: "{{hostvars[dashboard_host]['ansible_fqdn'] | regex_replace('\\.$', '')}}"

#Default Network Adapter
#network_interface: "otif1"
network_interface: "eno16777984"

# User running the playbooks
playbook_user: "{{ lookup('env','USER') }}"

# Home folder for the playbook_user
playbook_user_home: "{{ lookup('env','HOME') }}"

# DEPRECATED - Location where to download/find the packages (wget) 
# default_download_folder: "{{ lookup('env','HOME') }}/otif-packages"

# Location for Data (psql, mongo, kafka)
#custom_data_location: /data 
#custom_data_location: /actu02

# Master db name, username and password
# Use these as global defaults for db names, username and password.
master_dbname: magellan
master_username: maguser
master_password: Mage11an
# Password for 'postgres' admin
psql_admin_password: psql-admin
