---

- hosts: wsm-crawler

  tasks:

  - name: Configure InfoFusion Crawler for Web & Social Media 16.2 VM
    include_role:
      name: config_wsm_crawler_vm
    tags: 'install-wsm-crawler-vm'
    when: inventory_hostname in groups['wsm-crawler']

