---

- hosts: ecm-crawler

  tasks:

  - name: Install InfoFusion Crawler for ECM
    include_role:
      name: install_ecm_crawler
    tags: 'install-ecm-crawler'
    when: inventory_hostname in groups['ecm-crawler']


