---

- hosts: kafka, pipeline

  tasks:

  - name: Install Kafka for InfoFusion - dependency for all WSM Crawlers
    include_role:
      name: install_kafka
    tags: 'install-kafka'
    when: inventory_hostname in groups['kafka']

