---

- hosts: text-mining, pipeline
  serial: 1

  tasks: 

  - name: Deploy InfoFusion Text Mining
    include_role:
      name: install_text_mining
    tags: 'install-text-mining'
    when: inventory_hostname in groups['text-mining']    


