---

- hosts: pipeline, zookeeper, kafka, mongodb, text-mining, wsm-crawler

  tasks:

  - name: Deploy InfoFusion Ingestion Pipeline
    include_role:
      name: install_pipeline
    tags: 'install-pipeline'
    when: inventory_hostname in groups['pipeline']

