---

# First thing first - deploy Zookeeper used for Service Registry and centralized configuration
- import_playbook: deploy-zookeeper.yml
  
# The follwoing tasks manage deployement of dependencies
# Java, PostgreSQL, MongoDB

- import_playbook: deploy-otif-dependencies.yml
 
# The following tasks manage deployement of InfoFusion services

- import_playbook: deploy-kafka.yml

- import_playbook: deploy-text-mining.yml

- import_playbook: deploy-dashboard.yml

- import_playbook: deploy-wsm-crawler.yml

- import_playbook: deploy-pipeline.yml

#- import_playbook: deploy-ecm-crawler.yml

#- import_playbook: deploy-search.yml   

- import_playbook: summary.yml

