---

- hosts: web-crawler

  tasks:

  - name: Install InfoFusion Crawler for Web & Social Media
    include_role:
      name: install_web_crawler
    tags: 'install-web-crawler'
    when: inventory_hostname in groups['_web-crawler']


