---
  
# The following tasks initialize nodes
  
- import_playbook: init-nodes.yml

# The follwoing tasks manage deployement of dependencies

- import_playbook: deploy-otif-dependencies.yml
 
# The following tasks manage deployement of InfoFusion services

- import_playbook: deploy-zookeeper.yml

- import_playbook: deploy-text-mining.yml

- import_playbook: deploy-pipeline.yml

- import_playbook: deploy-wsm-crawler.yml

- import_playbook: deploy-ecm-crawler.yml

- import_playbook: deploy-search.yml   

