---
# defaults file for install_psql

# See also into inventory/group_vars/postgresql.yml for other global variables vailable for the group

# Install PostgreSQL 9.6 by default
maj_version: 9
min_version: 6

# use RPM release 3 (9.6-3)
psql_rpm_release: 3

# Password for PostgreSQL user
psql_admin_pw: "{{ psql_admin_password }}"

# Default DB, user and pw
psql_otif_db: "{{ master_dbname }}"
psql_otif_un: "{{ master_username }}"
psql_otif_pw: "{{ master_password }}"
# Set default privileges for the otif admin user
psql_otif_priv: ALL

# Default port to use
psql_port: 5432

# Remove existing PostgreSQL
remove_psql: true

# Change PostgreSQL config to allow remote connections and enable authentication using md5
update_config: yes

# Set the following to true to crate a ~/pgpass file 
# This will allow to use psql and pass password automatically
# using 'psql otif-admin -d infofusion'
# Needed to run the SQL queries needed to initialize the InfoFusion database
# For improved security, this file can be deleted once installation is completed
create_pgpass: true
