---
# tasks file for install_zookeeper


- debug:
    msg: "Zookeeper will be installed using '{{ zookeeper_installer.path }}'"

- debug:
    msg: "Zookeeper will be installed in {{ zookeeper_installation_path }}"

- name: Executing Zookeeper installer in console mode
  expect:
    command: "{{ zookeeper_installer.path }} -i console"
    echo: yes
    timeout: 60
    responses:
      .*to reach the end of this text.*: "skip"
      PRESS \<ENTER\> TO CONTINUE: ""
      .*DO YOU ACCEPT THE TERMS.*: "Y"
      .*ENTER AN ABSOLUTE PATH.*: "{{ zookeeper_installation_path }}"
      .*IS THIS CORRECT.*: "Y"
      .*Current Host.*: "{{ zookeeper_hostname }}"
      .*TO ACCEPT THE DEFAULT.*: ""
      '.*TO EXIT THE INSTALLER.*': ""
  register: installer_output

- debug:
    var: installer_output.stdout_lines

- pause:
    prompt: "Installation completed. Zookeeper should have been installed."
  when: with_pause

