---
# tasks file for install_zookeeper

- name: Make sure Zookeeper is removed if it exists
  block:
    
    - name: Check if the ot-zk.service exists
      stat:
        path: /etc/systemd/system/multi-user.target.wants/ot-zk.service
      register: service_is_there

    - name: Remove service
      command: "{{ USER_INSTALL_DIR }}/bin/otif.sh remove"
      register: zk_removal
      failed_when: zk_removal.rc != 0
      when: service_is_there.stat.exists == True
      
    - name: Remove Zookeeper directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ USER_INSTALL_DIR }}"        

  when: remove_zookeeper  

#- pause:
#    prompt: "Zookeeper should not be there!"
 
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "unzip"

- name: Make sure download folder exists
  include_role:
    name: common
    tasks_from: create_download_folder.yml

- name: Copy the Zookeeper package
  copy:
    src: "{{ download_folder }}/{{ otif_zookeeper_package }}"
    dest: "{{ download_folder }}/{{ otif_zookeeper_package }}"
    owner: "{{ playbook_user }}"
    group: "{{ playbook_user }}"
    mode: u+x

- name: Prepare silent mode response file
  template:
    src=otif-zookeeper.properties.j2
    dest={{ download_folder }}/otif-zookeeper.properties

- name: Run installer in silent mode
  command: "{{ download_folder }}/{{ otif_zookeeper_package }} -i silent -f {{ download_folder }}/otif-zookeeper.properties"
  ignore_errors: yes
  register: silent_mode
  failed_when: silent_mode.stdout  != ""

- name: Wait Zookeeper to be listening on port 2181
  wait_for:
    host: "127.0.0.1"
    port: "{{ item }}"
    delay: 5
    state: started
  with_items:
    - "2181"

