---
# tasks file for install_zookeeper

- name: Deploy Zookeeper for InfoFusion
  block:

    - name: Initialize and setup dependencies ...
      include_tasks: setup_zookeeper.yml

    - name: Remove Zookeeper if needed ...
      include_tasks: remove_zookeeper.yml

    - name: Install Zookeeper for InfoFusion
      include_tasks: install_zookeeper.yml

    - name: Configure Zookeeper for InfoFusion
      include_tasks: configure_zookeeper.yml

    - name: Start Zookeeper for InfoFusion
      include_tasks: start_zookeeper.yml

  when: inventory_hostname in groups['zookeeper']

