---
# tasks file for install_zookeeper


- name: Make sure Zookeeper is removed if it exists
  block:

    - name: Check if zookeeper is in the InstallAnywhere registry
      stat:
        path: /var/.com.zerog.registry.xml
      register: installanywhere_registry_is_there

    - name: If Registry is present ...
      block:

      - name: Look if Zookeeper is already registred
        xml:
          path: /var/.com.zerog.registry.xml
          xpath: /registry/products/product//feature[@short_name='Zookeeper']
          count: yes
        register: hits
        when: installanywhere_registry_is_there.stat.exists == true

      - name: If InstallAnyWhere Registry is aware of Zookeeper   
        block:

          - name: Get location where Zookeeper is already installed
            xml:
              path: /var/.com.zerog.registry.xml
              xpath: /registry/products/product[@name='Zookeeper for OpenText InfoFusion']
              content: attribute
              attribute: location
            register: zk_location

          - debug:
              msg: "Zookeeper is already installed in {{ zk_location.matches[0].product.location }}."

          - name: Removing Zookeeper ...
            expect:
              command: "{{ zookeeper_installer.path }} -i console"
              echo: yes
              timeout: 30
              responses:
                .*Choose Instance Management Option.*: "2"
                .*Choose the instance to modify.*: "1"
                .*DEFAULT.*: "1"
                .*TO CONTINUE.*: ""
            register: installer_output  

          - debug:
              var: installer_output.stdout_lines

          - name: Removing Zookeeper directory
            file:
              path: "{{ item }}"
              state: absent
            with_items:
              - "{{ zk_location.matches[0].product.location }}"

          - pause:
              prompt: "Removal completed. Zookeeper should have been removed."
            when: with_pause

        when: hits.count > 0 

      when: installanywhere_registry_is_there.stat.exists == true

  when: remove_zookeeper

