---
# tasks file for configure_zookeeper

- name: start Zookeeper services
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item.name }}"
  with_items:
    - { name: ot-zk-1 }

- name: Wait until Zookeeper is listening on port 2181
  wait_for:
    host: "{{ zookeeper_hostname }}"
    port: "{{ item.port }}"
    delay: 5
    state: started
  with_items:
    - { port: 2181 }
