---
# vars file for get_host_info

host_ip: "{{ hostvars[ansible_hostname]['ansible_' ~ network_interface].ipv4.address }}"

# Free space on hard disk
hd_total:  "{% for mount in ansible_mounts %}{% if mount.mount == '/' %}{{ mount.size_total }}{% endif %}{% endfor %}"
hd_free: "{% for mount in ansible_mounts %}{% if mount.mount == '/' %}{{ mount.size_available }}{% endif %}{% endfor %}"
hd_total_pretty: "{% for mount in ansible_mounts %}{% if mount.mount == '/' %}{{ (mount.size_total|int/1000000000)|round(1, 'common') }}GB{% endif %}{% endfor %}"
hd_free_pretty: "{% for mount in ansible_mounts %}{% if mount.mount == '/' %}{{ (mount.size_available|int/1000000000)|round(1, 'common') }}GB{% endif %}{% endfor %}"

mem_total: "{{ ansible_memtotal_mb }}"
mem_total_pretty: "{{ (ansible_memtotal_mb|int/1000)|round(1,'common') }}GB" 
mem_free: "{{ ansible_memfree_mb }}"
mem_free_pretty: "{{ (ansible_memfree_mb|int/1000)|round(1,'common') }}GB"

host_processor: "{% for processor in ansible_processor %}{% if loop.index <= 3 %}{{ processor|regex_replace('^0$')|replace('GenuineIntel', '')|replace('(R) ', ' ')|replace('Core(TM) ','')|regex_replace('[ ]+',' ') }}{% endif %}{% endfor %} with {{ ansible_processor_vcpus }} cores"
host_core: "{{ ansible_processor_vcpus }}"

os_distribution: "{{ ansible_distribution ~ ' ' ~ ansible_distribution_major_version ~ ' / ' ~ ansible_distribution_release ~ ' ' ~ ansible_distribution_version }}"
 
