---
# tasks file for update_hostname

- name: Reconfigure InfoFusion WSM Crawler
  include_tasks: configure_wsm_crawler.yml
  when: inventory_hostname in groups['wsm-crawler']

- name: Reconfigure InfoFusion Pipeline
  include_tasks: configure_pipeline.yml
  when: inventory_hostname in groups['pipeline']

- name: Reconfigure Magellan Text Mining
  include_tasks: configure_text_mining.yml
  when: inventory_hostname in groups['text-mining']

- name: Reconfigure InfoFusion Dashboard
  include_tasks: configure_dashboard.yml
  when: inventory_hostname in groups['dashboard']


