---

- name: Create Magellan databases
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{psql_otif_db}}_{{ item }}"
    owner: "{{ psql_otif_un }}"
    encoding: UTF-8
    state: present
  with_items:
    - wsm
    - ecm
    - dashboard
    - is
  when: inventory_hostname in groups['wsm-crawler']

- name: Create Magellan databases
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{psql_otif_db}}"
    owner: "{{ psql_otif_un }}"
    encoding: UTF-8
    state: present
  when: inventory_hostname in groups['pipeline']

- name: Ensure no other user can access the database
  become: true
  become_user: postgres
  postgresql_privs:
    db: "{{ psql_otif_db }}"
    role: PUBLIC
    type: database
    priv: ALL
    state: absent
  when: inventory_hostname in groups['pipeline']
