---
# tasks file for install_mongodb

- name: Installation tasks for MongoDB
  block:

    - name: Install Python dependencies ...
      yum:
        name: "{{ item }}"
      with_items:
        - python-setuptools
        - gcc
        - make
        - python-devel
        - libxml2-devel
        - libxslt-devel

    - name: Make sure MongoDB is not already running
      become: true
      service:
        name: mongod
        state: stopped
      ignore_errors: yes      
 
    - name: Uninstall the packages
      become: true
      yum:
        name: "{{item}}"
        state: absent
      with_items: "{{ mongo_packages }}*"
      when: remove_mongodb

    - name: Remove data & log folders from default location
      become: true
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "/var/log/mongodb"
        - "/var/lib/mongo"
        - "/etc/mongod.conf"
        - "/tmp/mongodb-27017.sock"
      when: remove_mongo_data and custom_data_location is not defined
 
    - name: Remove data & log folders from custom location
      become: true
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - "/var/log/mongodb"
        - "{{ custom_data_location }}/mongo"
        - "/etc/mongod.conf"
      when: remove_mongo_data and custom_data_location is defined

    - name: Install packages dependencies
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ mongo_packages_dependencies | default([]) }}"

    - name: Install pymongo dependency
      become: true
      easy_install:
       name: pymongo
       state: latest
  
    - name: Add MongoDB repository
      become: true
      yum_repository:
        name: "mongodb-org-{{ mongo_version }}"
        description: 'MongoDB Repository'
        baseurl: "{{ mongo_repo_baseurl }}"
        gpgcheck: "{{ mongo_repo_gpgcheck }}"
        gpgkey: "{{ mongo_repo_gpgkey }}"

    - name: Install MongoDB Packages
      become: true
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ mongo_packages }}"
  
  when: inventory_hostname in groups['mongodb']
 
