---

- name: Restart MongoDB
  become: true
  service:
    name: mongod
    state: restarted

- name: Wait MongoDB port is listening
  wait_for: 
    host: "127.0.0.1"
    port: "{{ mongo_port }}"
    delay: 5
    state: started
