---
# tasks file for configure_wsm_crawler

- name: Make sure the {{ master_dbname }} exists in postgresql.
  postgresql_db:
    name: "{{ master_dbname }}_wsm"
    login_user: postgres
    login_password: "{{ psql_admin_password }}"
    owner: "{{ master_username }}"
    encoding: UTF-8
    state: present  

- name: Create query to add admin user to the database
  template:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "add_admin.sql.j2", dest: "{{ crawler_installation_path }}/etc/add_admin.sql" }

- name: Initialize the database used by InfoFusion Crawler for Web & Social Media
#  become: true
#  become_user: "{{ playbook_user }}"
  shell: "{{ item.command }}"
  with_items:
    - { command: "PGPASSWORD={{ master_password }} psql {{ master_username }} -d {{ master_dbname }}_wsm -f {{ crawler_installation_path }}/etc/otif-wsm-crawler-schema.sql" }
    - { command: "PGPASSWORD={{ master_password }} psql {{ master_username }} -d {{ master_dbname }}_wsm -f {{ crawler_installation_path }}/etc/add_admin.sql" }
    
- name: Open port 10100 used to access InfoFusion Crawler for Web & Social Media Admin UI
  become: true
  ignore_errors: true
  firewalld:
    zone: public
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "10010"

- name: Restart WSM Service
  systemd:
    state: restarted
    daemon_reload: yes
    name: otif-wsm-crawler-1

- name: Authenticate to the WSM Crawler Admin UI to get cookie
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/authentication/login"
    method: POST
    body: "username={{ master_username }}&password={{ master_password }}"
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login

- name: Create a sample Twitter Access Token for Twitter Search API
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/crawlertypes/Twitter%20Search/configs"
    method: POST
    body: >
      {"config_name":"test","props":[{"prop_name":"CONSUMER_KEY","prop_value":"jCF3SP0aFiqkDwvw5UO52pzEm"},
      {"prop_name":"CONSUMER_SECRET","prop_value":"9CJYOOBR9mSBL0gC1alejvyvfICXFiFMts66NKIk3vInQLj3FZ"},
      {"prop_name":"ACCESS_TOKEN","prop_value":"12842652-i1qoXufhBX7ZHyrq6xyA32Z3SGVTvRBRFzyNlWSmz"},
      {"prop_name":"ACCESS_SECRET","prop_value":"COlIFpmBWjaHs66HhkwwIUTFCUkiDCoyfyWaOGtUT5oSb"}]}
    status_code: 201, 400
    body_format: json
    timeout: 30
    headers:
      Cookie: "{{login.set_cookie}}"
  register: request_otif

- name: Create a sample Twitter Access Token for Twitter Stream API
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/crawlertypes/Twitter%20Stream/configs"
    method: POST
    body: >
      {"config_name":"test","props":[{"prop_name":"CONSUMER_KEY","prop_value":"jCF3SP0aFiqkDwvw5UO52pzEm"},
      {"prop_name":"CONSUMER_SECRET","prop_value":"9CJYOOBR9mSBL0gC1alejvyvfICXFiFMts66NKIk3vInQLj3FZ"},
      {"prop_name":"ACCESS_TOKEN","prop_value":"12842652-i1qoXufhBX7ZHyrq6xyA32Z3SGVTvRBRFzyNlWSmz"},
      {"prop_name":"ACCESS_SECRET","prop_value":"COlIFpmBWjaHs66HhkwwIUTFCUkiDCoyfyWaOGtUT5oSb"}]}
    status_code: 201, 400
    body_format: json
    timeout: 30
    headers:
      Cookie: "{{login.set_cookie}}"
  register: request_otif

- name:
  debug:
    var: request_otif

- name: Create a sample Twitter crawling job
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/jobs"
    method: POST
    body: >
      {"schedule_info":{"repeat_count":0,"recurrence":0},
      "search_text":{"criteria":{"type":"twitter_search","words":{"include_all_these":[],"include_any_of_these":[],
      "not_include_these":[],"include_these_hashtags":["#opentext"],"exact_phrase":null},
      "dates":null,"language":null,"surrounding_to":null,"people":null,
      "others":{"positive":false,"negative":false,"question":false,"include_retweets":false,"result_type":"mixed"}}},
      "job_id":1,"name":"Sample Twitter Crawling Job","status":"Unscheduled",
      "description":"This is a sample Twitter crawling job",
      "crawler_type":"Twitter Search","job_group":"OpenText","exec_info":{"id":0,"job_id":1}}
    status_code: 201, 400
    body_format: json
    timeout: 10
    headers:
      Cookie: "{{login.set_cookie}}"
  register: request_otif

- name:
  debug:
    var: request_otif

- name: Create a sample Web crawling job
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/jobs"
    method: POST
    body: >
      {"schedule_info":{"repeat_count":0,"recurrence":0},
      "search_text":{"numberOfCycles":5,"batchSize":50,"configuration":{},
      "urls":["http://investors.opentext.com/press-releases?aa7708e5_year[value]=_none"],
      "url_filters":[{"expression":".*/amp$","type":"EXCLUDE"},
      {"expression":"http://investors.opentext.com/press-releases*","type":"INCLUDE"},
      {"expression":"http://investors.opentext.com/news-releases/news-release-details*","type":"INCLUDE"},{"expression":".","type":"EXCLUDE"}],
      "ingestion_filters":[{"expression":"http://investors.opentext.com/press-releases*","type":"EXCLUDE"},
      {"expression":".","type":"INCLUDE"}],
      "pipeline_custom_properties":[{"wikipedia_url":"https://en.wikipedia.org/wiki/OpenText"}],
      "scrapingRules":[{"targetField":"document.metadata.attributes.creationDate",
      "textExtraction":{"concatenate":false,"xpaths":["//div[contains(@class,'news-date')]/div/text()"]},
      "textTransformation":[{"type":"dateFormatting","parameters":{"format":"MMM d, YYY"}}]}]},
      "job_id":2,"name":"Sample Web Crawling Job","status":"Unscheduled",
      "description":"This is a sample Web crawling job","crawler_type":"Web","job_group":"OpenText","exec_info":{"id":0,"job_id":2}}
    status_code: 201, 400
    body_format: json
    timeout: 10
    headers:
      Cookie: "{{login.set_cookie}}"
  register: request_otif

- name:
  debug:
    var: request_otif

