---
# tasks file for configure_wsm_crawler

- name: Activate Dashboard
  become: true
  lineinfile:
    dest: "{{ crawler_installation_path }}/etc/{{ item.file }}"
    regexp: "{{item.regexp }}"
    line: "{{item.line}}"
  with_items:
    - { file: "otif-crawler.properties", regexp: "dashboard.notifier.enabled=", line: "dashboard.notifier.enabled=true" }
    - { file: "otif-crawler.properties", regexp: "dashboard.notifier.component.adminurl=", line: "dashboard.notifier.component.adminurl=http://{{ wsm_crawler_hostname }}:10010" }
    - { file: "otif-crawler.properties", regexp: "dashboard.service.url=", line: "dashboard.service.url=http://{{ dashboard_hostname }}:10020/otif-dashboard-api/api/v1" }
    - { file: "otif-crawler.properties", regexp: "dashboard.service.password=", line: "dashboard.service.password=admin" }
    - { file: "crawleradmin.properties", regexp: "dashboard.service.url=", line: "dashboard.service.url=http://{{ dashboard_hostname }}:10020/otif-dashboard-api/api/v1" }
    - { file: "crawleradmin.properties", regexp: "dashboard.component.adminurl=", line: "dashboard.component.adminurl=http://{{ wsm_crawler_fqdn }}:10010" }

- name: Make sure the {{ master_dbname }}_wsm exists in postgresql.
  postgresql_db:
    name: "{{ master_dbname }}_wsm"
    login_user: postgres
    login_password: "{{ psql_admin_password }}"
    owner: "{{ master_username }}"
    encoding: UTF-8
    state: present  

- name: Create query to add admin user to the database
  template:
    src:  "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "add_admin.sql.j2", dest: "{{ crawler_installation_path }}/etc/add_admin.sql" }

- name: Initialize the database used by InfoFusion Crawler for Web & Social Media
#  become: true
#  become_user: "{{ playbook_user }}"
  shell: "{{ item.command }}"
  with_items:
    - { command: "PGPASSWORD={{ master_password }} psql {{ master_username }} -d {{ master_dbname }}_wsm -f {{ crawler_installation_path }}/etc/otif-wsm-crawler-schema.sql" }
    - { command: "PGPASSWORD={{ master_password }} psql {{ master_username }} -d {{ master_dbname }}_wsm -f {{ crawler_installation_path }}/etc/add_admin.sql" }

- name: Open port 10010 used to access InfoFusion Crawler for Web & Social Media Admin UI
  become: true
  ignore_errors: true
  firewalld:
    zone: public
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  with_items:
    - "10010"

- name: Restart WSM Service
  systemd:
    state: restarted
    daemon_reload: yes
    name: otif-wsm-crawler-1

- name: Wait for WS Crawler service on port 10010
  wait_for:
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    delay: 5
    timeout: 30
    state: started
  with_items:
    - { host: "{{wsm_crawler_hostname}}", port: 10010 }
  register: wait

- name: Authenticate to the WSM Crawler Admin UI to get cookie
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/authentication/login"
    method: POST
#    body: "username={{ master_username }}&password={{ master_password }}"
    body: "username=admin&password=admin"
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login

- name: Create a sample Twitter Access Token for Twitter Search API
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/crawlertypes/Twitter%20Search/configs"
    method: POST
    body: >
      {"config_name":"test","props":[{"prop_name":"CONSUMER_KEY","prop_value":"jCF3SP0aFiqkDwvw5UO52pzEm"},
      {"prop_name":"CONSUMER_SECRET","prop_value":"9CJYOOBR9mSBL0gC1alejvyvfICXFiFMts66NKIk3vInQLj3FZ"},
      {"prop_name":"ACCESS_TOKEN","prop_value":"12842652-i1qoXufhBX7ZHyrq6xyA32Z3SGVTvRBRFzyNlWSmz"},
      {"prop_name":"ACCESS_SECRET","prop_value":"COlIFpmBWjaHs66HhkwwIUTFCUkiDCoyfyWaOGtUT5oSb"}]}
    status_code: 201, 400
    body_format: json
    timeout: 30
    headers:
      Cookie: "{{login.set_cookie}}"
  register: request_otif

- name: Create a sample Twitter Access Token for Twitter Stream API
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/crawlertypes/Twitter%20Stream/configs"
    method: POST
    body: >
      {"config_name":"test","props":[{"prop_name":"CONSUMER_KEY","prop_value":"jCF3SP0aFiqkDwvw5UO52pzEm"},
      {"prop_name":"CONSUMER_SECRET","prop_value":"9CJYOOBR9mSBL0gC1alejvyvfICXFiFMts66NKIk3vInQLj3FZ"},
      {"prop_name":"ACCESS_TOKEN","prop_value":"12842652-i1qoXufhBX7ZHyrq6xyA32Z3SGVTvRBRFzyNlWSmz"},
      {"prop_name":"ACCESS_SECRET","prop_value":"COlIFpmBWjaHs66HhkwwIUTFCUkiDCoyfyWaOGtUT5oSb"}]}
    status_code: 201, 400
    body_format: json
    timeout: 30
    headers:
      Cookie: "{{login.set_cookie}}"
  register: request_otif

- name:
  debug:
    var: request_otif

- name: Create a sample Twitter crawling job
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/jobs"
    method: POST
    body: >
      {"schedule_info":{"repeat_count":0,"recurrence":0},
      "search_text":{"criteria":{"type":"twitter_search","words":{"include_all_these":[],"include_any_of_these":[],
      "not_include_these":[],"include_these_hashtags":["#opentext"],"exact_phrase":null},
      "dates":null,"language":null,"surrounding_to":null,"people":null,
      "others":{"positive":false,"negative":false,"question":false,"include_retweets":false,"result_type":"mixed"}}},
      "job_id":1,"name":"Sample Twitter Crawling Job","status":"Unscheduled",
      "description":"This is a sample Twitter crawling job",
      "crawler_type":"Twitter Search","job_group":"OpenText","exec_info":{"id":0,"job_id":1}}
    status_code: 201, 400
    body_format: json
    timeout: 10
    headers:
      Cookie: "{{login.set_cookie}}"
  register: request_otif

- name:
  debug:
    var: request_otif

- name: Create a sample Web crawling job
  uri:
    url: "http://{{ wsm_crawler_fqdn }}:10010/crawlers-admin/rest/v1/jobs"
    method: POST
    body: >
      {"schedule_info":{"repeat_count":0,"recurrence":0},"search_text":{"numberOfCycles":3,"batchSize":50,
      "configuration":{},"urls":["https://blogs.opentext.com/"],
      "url_filters":[{"expression":"\\/(author|category|feed|tag)\\/","type":"EXCLUDE"},{"expression":"\\/(xmlrpc|wp-)","type":"EXCLUDE"},
      {"expression":"https:\\/\\/blogs.opentext.com\\/.*","type":"INCLUDE"},{"expression":".","type":"EXCLUDE"}],
      "ingestion_filters":[{"expression":"page=","type":"EXCLUDE"},{"expression":"https:\\/\\/blogs.opentext.com\\/$","type":"EXCLUDE"},{"expression":".","type":"INCLUDE"}],
      "content_filters":[{"expression":".","type":"EXCLUDE"}],
      "scrapingRules":[{"targetField":"document.metadata.attributes.creationDate",
      "textExtraction":{"concatenate":false,"xpaths":["//meta[@property=\"article:published_time\"]/@content"]},
      "textTransformation":[{"type":"dateFormatting","parameters":{"format":"yyyy-MM-dd'T'hh:mm:ssXXX"}}]}],
      "pipeline_custom_properties":{"source":"OpenText Blogs"}},
      "job_id":2,"name":"Sample Web Crawling Job","creation_date":"2018-05-04T06:41:42.485-0700",
      "status":"Completed","date_modified":"2018-05-04T07:26:25.457-0700","crawler_type":"Web",
      "job_group":"OpenText","exec_info":{"id":2,"job_id":2,"last_run":"2018-05-04T07:10:18.754-0700","status":"Completed","message":"Job execution completed successfully"}}
    status_code: 201, 400
    body_format: json
    timeout: 10
    headers:
      Cookie: "{{login.set_cookie}}"
  register: request_otif

- name:
  debug:
    var: request_otif

