---
# tasks file for install_wsm_crawler

- name: Make sure Crawler for Web & Social Media is removed if it exists
  block:

    - name: Check if the otif-wsm-crawler-1.service exists
      stat:
        path: /etc/systemd/system/multi-user.target.wants/otif-wsm-crawler-1.service
      register: service_is_there

    - name: Check if target directory exists
      stat:
        path: "{{ USER_INSTALL_DIR }}"
      register: directory_is_there

#    - pause:
#        prompt: "{{ service_is_there.stat.exists }} and {{ directory_is_there.stat.exists }}" 

    - name: Remove service
      command: "{{ USER_INSTALL_DIR }}/bin/otif.sh remove"
      register: crawler_removal
      failed_when: crawler_removal.rc != 0 
      when: 
        - service_is_there.stat.exists == True
        - directory_is_there.stat.exists == True
    
    - name: Delete existing services
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/systemd/system/infofusion-web-crawling-1.service"
        - "/etc/systemd/system/otif-wsm-crawler-1.service"

    - name: Remove Crawler for Web & Social Media directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ USER_INSTALL_DIR }}"

  when: remove_wsm_crawler

#- pause:
#    prompt: "Crawler for Web & Social Media should not be there!"

- name: Install dependencies (unzip)
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "unzip"

- name: Make sure download folder exists
  include_role:
    name: common
    tasks_from: create_download_folder.yml

- name: Copy the Crawler for Web & Social Media package
  copy:
    src: "{{ download_folder }}/{{ otif_wsm_crawler_package }}"
    dest: "{{ download_folder }}/{{ otif_wsm_crawler_package }}"
    owner: "{{ playbook_user }}"
    group: "{{ playbook_user }}"
    mode: u+x

- name: Prepare silent mode response file
  template:
    src: otif-wsm-crawler.properties.j2
    dest: "{{ download_folder }}/otif-wsm-crawler.properties"

- name: Run installer in silent mode
  command: "{{ download_folder }}/{{ otif_wsm_crawler_package }} -i silent -f {{ download_folder }}/otif-wsm-crawler.properties"
  ignore_errors: yes
  register: silent_mode
  failed_when: silent_mode.stdout  != ""



