---
# tasks file for install_wsm_crawler

- name: Testing services dependencies -  Zookeeper, Kafka, MongoDB
  wait_for:
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    delay: 5
    timeout: 10
    state: started
  with_items:
    - { host: "{{zookeeper_hostname}}", port: 2181 }
    - { host: "{{kafka_hostname}}", port: 9092 }
    - { host: "{{mongodb_hostname}}", port: 27017 }
  register: wait

- debug:
    msg: "WSM Crawler will be installed using '{{  wsm_crawler_installer.path }}'"

- debug:
    msg: "WSM Crawler will be installed in {{ crawler_installation_path }}"

- name: Executing WSM Crawler installer in console mode
  expect:
    command: "{{ wsm_crawler_installer.path }} -i console"
    echo: yes
    timeout: 60
    responses:
      .*to reach the end of this text.*: "skip"
      PRESS \<ENTER\> TO CONTINUE: ""
      .*DO YOU ACCEPT THE TERMS.*: "Y"
      .*Please choose a destination folder.*: "{{ crawler_installation_path }}"
      .*IS THIS CORRECT.*: "Y"
      .*unique suffix.*: "1"
      .*Run service as specified user.*: "0"
      .*Select Crawlers Component To Install.*: "1"
      .*Port Number.*: ""
      .*Please enter Provider.*: ""
      .*Please enter Database Host Name.*: "{{ wsm_crawler_hostname }}"
      .*Please enter Database for InfoFusion Crawler.*: "{{ master_dbname }}_wsm"
      .*Please enter Database Schema Name.*: ""
      .*Please enter Database User Name.*: "{{ master_username }}"
      .*Please enter Password.*: "{{ master_password }}"
      .*Please enter Zookeeper ensemble URL.*: "{{ zookeeper_hostname }}:2181"
      .*Please enter Twitter Service Name.*: ""
      .*Please enter Scheme.*: ""
      .*Please enter Twitter Service Host.*: "{{ wsm_crawler_hostname }}"
      .*Please enter Twitter Service Port.*: ""
      .*Please enter Kafka Client Id.*: ""
      .*Please enter Kafka URL.*: "{{ kafka_hostname }}:9092"
      .*Please enter Topic Name for Twitter.*: ""
      .*Please enter MongoDB Servers.*: "{{ mongodb_hostname }}:27017"
      .*Please enter Database Name.*: "{{ master_dbname }}"
      .*Please enter User Name.*: "{{ master_username }}"
#      .*Please enter Password.*: "{{ master_password }}"
      .*Please enter Kafka Servers.*: "{{ kafka_hostname }}:9092"
      .*Please enter Crawler Web Service Name.*: ""
      .*Please enter Topic Name for Web Crawler.*: ""
      .*TO EXIT THE INSTALLER.*: ""
  register: installer_output

- debug:
    var: installer_output.stdout_lines

- pause:
    prompt: "Installation completed. WSM Crawler will now be configured."
  when: with_pause



