---
# tasks file for install_web_crawler

- name: Prepare Installation
  include_tasks: checkup.yml

- name: Check if WSM Crawler needs to be removed ...
  include_role:
    name: remove_wsm_crawler
    tasks_from: remove_wsm_crawler
  when: remove_wsm-Crawler

- name: Install InfoFusion Crawler for Web & Social Media
  include_tasks: install_wsm_crawler.yml

- name: Configure InfoFusion Crawler for Web & Social Media
  include_tasks: configure_wsm_crawler.yml

- name: Start InfoFusion Crawler for Web & Social Media
  include_tasks: start_wsm_crawler.yml


