---
# tasks file for start_web_crawler


- name: Enable service for Web & Social Media service
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item.name }}"
  with_items:
    - { name: otif-wsm-crawler-1 }
    - { name: infofusion-web-crawling-1 }

- name: Wait service depedencies for Crawler for Web & Social Media
  wait_for:
    host: "127.0.0.1"
    port: "{{ item }}"
    delay: 5
    state: started
  with_items:
    - "10010"
    - "10011"

- name:
  vars:
    msg: |
         Magellan Crawler for Web & Social Media has been configured on {{ wsm_crawler_hostname }}.
         Two sample crawling jobs have been created to test with.
         You can validate deployement by opening http://{{ wsm_crawler_fqdn }}:10010
         or http://{{ ansible_host }}:10010
         Default credentials are admin/admin but user '{{ master_username }}/{{ master_password }}' has been added as well.
  debug:
    msg: "{{ msg.split('\n') }}"


